package game

const (
	PLATFORM_XJTY int32 = 1
	PLATFORM_IM   int32 = 2
	PLATFORM_YABO int32 = 3
	PLATFORM_FJ   int32 = 4
	PLATFORM_NEAL int32 = 5
	PLATFORM_M6   int32 = 6
	PLATFORM_SABA int32 = 7

	PLATFORM_HGUAN int32 = 29

	PLATFORM_YABO_IM int32 = 301
	PLATFORM_DEF     int32 = 9
	PLATFORM_FJ_GIF  int32 = 401

	VEDIOS_INFO_UPDATE_TM int32 = 5 * 60
)

const (
	DB_MATCH_HGUAN_IM   = "GS_REAL_TIME_EVENT_MATCH_HGUAN_IM"
	DB_MATCH_HGUAN_SABA = "GS_REAL_TIME_EVENT_MATCH_HGUAN_SABA"
)
